// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTokenButton: typeof import('./src/components/AddTokenButton.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AuthGuard: typeof import('./src/components/AuthGuard.vue')['default']
    AuthMenu: typeof import('./src/components/AuthMenu.vue')['default']
    AuthStatus: typeof import('./src/components/AuthStatus.vue')['default']
    BoolCheck: typeof import('./src/components/BoolCheck.vue')['default']
    ContractUI: typeof import('./src/components/ContractUI.vue')['default']
    CountDown: typeof import('./src/components/CountDown.vue')['default']
    Draw: typeof import('./src/components/Draw.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    EditableText: typeof import('./src/components/EditableText.vue')['default']
    FaqSection: typeof import('./src/components/FaqSection.vue')['default']
    FeedbackForm: typeof import('./src/components/FeedbackForm.vue')['default']
    FetchData: typeof import('./src/components/FetchData.vue')['default']
    HamburgerButton: typeof import('./src/components/HamburgerButton.vue')['default']
    InkStore: typeof import('./src/components/InkStore.vue')['default']
    JazzIcon: typeof import('./src/components/JazzIcon.vue')['default']
    ListGuard: typeof import('./src/components/ListGuard.vue')['default']
    LoadImage: typeof import('./src/components/LoadImage.vue')['default']
    MainNavbar: typeof import('./src/components/MainNavbar.vue')['default']
    ModalBox: typeof import('./src/components/ModalBox.vue')['default']
    NumberTicker: typeof import('./src/components/NumberTicker.vue')['default']
    NumberTicker1: typeof import('./src/components/NumberTicker1.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    QrCodeWidget: typeof import('./src/components/QrCodeWidget.vue')['default']
    RenderABI: typeof import('./src/components/RenderABI.vue')['default']
    RenderDate: typeof import('./src/components/RenderDate.vue')['default']
    RenderMarkdown: typeof import('./src/components/RenderMarkdown.vue')['default']
    RenderObject: typeof import('./src/components/RenderObject.vue')['default']
    RenderTable: typeof import('./src/components/RenderTable.vue')['default']
    ShareButtons: typeof import('./src/components/ShareButtons.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SocialIcons: typeof import('./src/components/SocialIcons.vue')['default']
    StepForm: typeof import('./src/components/StepForm.vue')['default']
    StepIcon: typeof import('./src/components/StepIcon.vue')['default']
    StepperFlow: typeof import('./src/components/StepperFlow.vue')['default']
    Studio: typeof import('./src/components/Studio.vue')['default']
    SVG: typeof import('./src/components/SVG.vue')['default']
    TokenCard: typeof import('./src/components/TokenCard.vue')['default']
    TokenIcon: typeof import('./src/components/TokenIcon.vue')['default']
    TokenMaterials: typeof import('./src/components/TokenMaterials.vue')['default']
    TokenModal: typeof import('./src/components/TokenModal.vue')['default']
    WalletAddress: typeof import('./src/components/WalletAddress.vue')['default']
    Whiteboard: typeof import('./src/components/Whiteboard.vue')['default']
  }
}

export { }
