// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTokenButton: typeof import('./components/AddTokenButton.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    AuthGuard: typeof import('./components/AuthGuard.vue')['default']
    AuthMenu: typeof import('./components/AuthMenu.vue')['default']
    AuthStatus: typeof import('./components/AuthStatus.vue')['default']
    BoolCheck: typeof import('./components/BoolCheck.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    ContractUI: typeof import('./components/ContractUI.vue')['default']
    CountDown: typeof import('./components/CountDown.vue')['default']
    DropDown: typeof import('./components/DropDown.vue')['default']
    EditableText: typeof import('./components/EditableText.vue')['default']
    FaqSection: typeof import('./components/FaqSection.vue')['default']
    FeedbackForm: typeof import('./components/FeedbackForm.vue')['default']
    FetchData: typeof import('./components/FetchData.vue')['default']
    HamburgerButton: typeof import('./components/HamburgerButton.vue')['default']
    InkStore: typeof import('./components/InkStore.vue')['default']
    JazzIcon: typeof import('./components/JazzIcon.vue')['default']
    ListGuard: typeof import('./components/ListGuard.vue')['default']
    LoadImage: typeof import('./components/LoadImage.vue')['default']
    MainNavbar: typeof import('./components/MainNavbar.vue')['default']
    ModalBox: typeof import('./components/ModalBox.vue')['default']
    NumberTicker: typeof import('./components/NumberTicker.vue')['default']
    NumberTicker1: typeof import('./components/NumberTicker1.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    QrCodeWidget: typeof import('./components/QrCodeWidget.vue')['default']
    RenderABI: typeof import('./components/RenderABI.vue')['default']
    RenderDate: typeof import('./components/RenderDate.vue')['default']
    RenderMarkdown: typeof import('./components/RenderMarkdown.vue')['default']
    RenderObject: typeof import('./components/RenderObject.vue')['default']
    RenderTable: typeof import('./components/RenderTable.vue')['default']
    ShareButtons: typeof import('./components/ShareButtons.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SocialIcons: typeof import('./components/SocialIcons.vue')['default']
    StepForm: typeof import('./components/StepForm.vue')['default']
    StepIcon: typeof import('./components/StepIcon.vue')['default']
    StepperFlow: typeof import('./components/StepperFlow.vue')['default']
    Studio: typeof import('./components/Studio.vue')['default']
    SVG: typeof import('./components/SVG.vue')['default']
    TokenCard: typeof import('./components/TokenCard.vue')['default']
    TokenIcon: typeof import('./components/TokenIcon.vue')['default']
    TokenMaterials: typeof import('./components/TokenMaterials.vue')['default']
    TokenModal: typeof import('./components/TokenModal.vue')['default']
    WalletAddress: typeof import('./components/WalletAddress.vue')['default']
    Whiteboard: typeof import('./components/Whiteboard.vue')['default']
  }
}

export { }
